# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-20 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu',
            name='isRecommended',
            field=models.IntegerField(choices=[(1, '是'), (2, '否')], verbose_name='是否内部推荐'),
        ),
    ]
