# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-29 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20171120_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('passwd', models.CharField(max_length=32, verbose_name='密码')),
            ],
        ),
    ]
